# Pre-commit configuration for agentic-spec
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Ruff linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.8.0
    hooks:
      # Run the linter (non-blocking, shows warnings)
      - id: ruff
        args: [--fix, --exit-zero]
      # Run the formatter
      - id: ruff-format

  # Standard pre-commit hooks for general quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Check for secrets
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: python-use-type-annotations

# Configure to run on commit
default_stages: [pre-commit]

# Fail fast - stop running hooks after first failure
fail_fast: false
