# Pre-commit configuration for agentic-spec
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Ruff linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.8.0
    hooks:
      # Run the linter with auto-fix
      - id: ruff
        args: [--fix, --exit-zero]
        # Allow hooks to modify files and auto-restage them
        stages: [pre-commit]
      # Run the formatter (auto-formats files)
      - id: ruff-format
        # Allow hooks to modify files and auto-restage them
        stages: [pre-commit]

  # Standard pre-commit hooks for general quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: debug-statements
        stages: [pre-commit]

  # Check for secrets
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
        stages: [pre-commit]
      - id: python-check-blanket-type-ignore
        stages: [pre-commit]
      - id: python-no-log-warn
        stages: [pre-commit]
      - id: python-use-type-annotations
        stages: [pre-commit]


# Configure to run on commit and allow modification
default_stages: [pre-commit]

# Don't fail fast - run all hooks to catch all issues
fail_fast: false

# Configure git to automatically restage files modified by hooks
# This prevents the "files were modified by hooks" issue
ci:
    autoupdate_schedule: weekly
    skip: []
